# Generated by Django 2.2.1 on 2019-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190517_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='semester',
            field=models.IntegerField(choices=[('first', 'first'), ('second', 'second')]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='grade',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=1),
        ),
    ]
