# Generated by Django 2.2.1 on 2019-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190517_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='semester',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second')], max_length=6),
        ),
    ]
